### ISSUE TITLE
[Error] Loading keybindings

### ISSUE THREAD

**Issue by MarioGK** [decaprime/Bloodstone#7]
Hello, the mod is giving an error on load:

`[Info   :   BepInEx] Loading [Bloodstone 0.1.6]
[Error  :Bloodstone] Error loading keybindings, using defaults:
[Error  :Bloodstone] System.TypeInitializationException: The type initializer for 'Bloodstone.API.KeybindManager' threw an exception.
 ---> System.TypeLoadException: Could not load type 'ProjectM.InputFlag' from assembly 'ProjectM.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Bloodstone.API.KeybindManager..cctor()
   --- End of inner exception stack trace ---
   at Bloodstone.API.KeybindManager.Load()
[Error  :   BepInEx] Error loading [Bloodstone 0.1.6]: System.TypeInitializationException: The type initializer for 'Bloodstone.API.KeybindManager' threw an exception.
 ---> System.TypeLoadException: Could not load type 'ProjectM.InputFlag' from assembly 'ProjectM.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Bloodstone.API.KeybindManager..cctor()
   --- End of inner exception stack trace ---
   at Bloodstone.API.KeybindManager.Load()
   at Bloodstone.BloodstonePlugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 134
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411`

**Comment by theotherp** [comment]
They're still working on 1.0 compatibility: https://github.com/decaprime/Bloodstone/pull/6
